name: Automated Workflow

on:
  workflow_dispatch:  # 手動実行を許可するトリガー
    inputs:
      tag_name:
        description: 'Tag name for the release'  # ユーザーが入力するタグ名の説明
        required: true  # 必須入力
        default: ''  # デフォルトの値（空に設定）

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_release_draft:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: 'Release ${{ github.event.inputs.tag_name }}'
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_pr:
    needs: create_release_draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request to develop
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: develop
          title: 'Merge Release ${{ github.event.inputs.tag_name }} to Develop'
          commit-message: 'Automated PR to merge release branch to develop'
          body: 'This PR merges the latest changes from the release branch to develop.'
          base: develop
          head: ${{ github.event.inputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
