name: Automated Workflow

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'The target branch to merge the source branch into'
        required: true
        default: 'develop'

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      TAG_NAME: ${{ steps.extract_tag.outputs.TAG_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name from branch
        id: extract_tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/heads/release/}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

  create_release_draft:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ needs.create_tag.outputs.TAG_NAME }}
          name: 'Release ${{ needs.create_tag.outputs.TAG_NAME }}'
          version: ${{ needs.create_tag.outputs.TAG_NAME }}
          prerelease: false
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create_pr:
    needs: create_release_draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request to target branch
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.ref_name }}  # Current branch (source branch)
          title: 'Merge Release from ${{ github.ref_name }} to ${{ github.event.inputs.target_branch }}'
          commit-message: 'Automated PR to merge release branch to target branch'
          body: 'This PR merges the latest changes from the current branch to the target branch.'
          base: ${{ github.event.inputs.target_branch }}  # Target branch for the PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
